[feat] 개별 프로필 조회API 구현
Team-Going/Going-Server pull request #139
Opened 2024-03-03 13:34 UTC by gardening-y

## Related Issue 📌

## Description ✔️
-

2024-03-03 15:32 UTC, SunwoongH requested changes
고생 많으셨습니다!

2024-03-03 15:32 UTC, SunwoongH commented on doorip-api/src/main/java/org/doorip/trip/dto/response/TripParticipantProfileResponse.java
> +        );
Builder 어노테이션을 적용해봐도 좋을 것 같습니다~

2024-03-03 15:32 UTC, SunwoongH commented on doorip-api/src/main/java/org/doorip/trip/service/TripDetailService.java
> +    }
메서드명 Camel Case 확인 한 번 부탁드립니다. 그리고 NPE의 경우, 
<img width="293" alt="스크린샷 2024-03-04 오전 12 26 55" src="https://github.com/Team-Going/Going-Server/assets/81796317/f3d35ced-65d9-40fe-a034-f8941f64f19a">
numResult가 int 기본 자료형으로 선언되어 있어서 발생하는 것 같습니다. 해당 자료형을 Integer 래퍼 클래스로 변경하면 null 값을 가질 수 있어서 해결될 것 같은데 확인 가능할까요?

2024-03-03 16:17 UTC, gardening-y commented on doorip-api/src/main/java/org/doorip/trip/service/TripDetailService.java
> +    }
변경해보니 response builder에서 user.getResult().getNumResult()를 사용하는데 getResult() 자체가 null 이기 때문에 getNumResult()를 꺼내오면 NPE가 발생하는것으로 확인됩니다. null을 그대로 반환하려면 다시 user.getResult()를 null인지 아닌지 확인하는 메서드가 필요한데 이 메서드를 추가해서 null을 반환하는 것으로 변경하는게 나을까요?! 좋은 의견있으면 알려주세요!

2024-03-04 07:46 UTC, SunwoongH commented on doorip-api/src/main/java/org/doorip/trip/service/TripDetailService.java
> +    }
제가 잘못 이해했었네요! 저도 조금 더 고민이 필요할 것 같습니다. 우선 2차 스프린트 기간 내에 API가 배포되어야 해서 현재 기능적인 문제는 없으니 현재 PR 머지 후 이슈를 새롭게 생성해서 리팩터링을 진행해 보면 좋을 것 같습니다. 같이 고민해 보겠습니다!

2024-03-04 07:46 UTC, SunwoongH approved these changes

2024-03-04 07:55 UTC, merged